#+STARTUP: overview

* .dir-locals.el

#+begin_src elisp
  ((nil . ((compile-command . "cd ~/github/fdload_dfs && make _tom"))))
#+end_src

#+begin_src elisp
  ((nil . ((compile-command . "cd D:\\tom\\github\\fdload_dfs && make _tom"))))
#+end_src

* memory map ramblings

Ramblings indeed.

** Zero page use and notes

| Region | What               |
|--------+--------------------|
| $0x    | current effect     |
| $1x    | current effect     |
| $2x    | current effect     |
| $3x    | current effect     |
| $4x    | current effect     |
| $5x    | current effect     |
| $6x    | current effect     |
| $7x    | current effect     |
| $8x    | transition effect? |
| $9x    | transition effect? |
| $Ax    | transition effect? |
| $Bx    | music?             |
| $Cx    | music?             |
| $Dx    | music?             |
| $Ex    | framework          |
| $Fx    | framework/Acorn OS |

- "Acorn OS" covers $FC, which is used to store the accumulator as
  part of the IRQ handler preamble in the MOS ROM. This is not free
  for use.
- $F4 should not be set. ROMSEL is readable on the Master so there's
  no need for a RAM copy. Anything that needs to save and restore
  ROMSEL can just read the value from $FE30. (Same applies to ACCCON
  at $FE34.)
- do transition effect and current effect even need to be separate?

** Main memory use and notes

| Page | What       | Notes                         |
|------+------------+-------------------------------|
|    1 | (stack)    | stack                         |
|    2 | reserved   | IRQ1V and global entry points |
|    3 | sector 0   | used while loading            |
|    4 | sector 1   | used while loading            |
|    5 | sector 2   | used while loading            |
|    6 | sector 3   | used while loading            |
|    7 | sector 4   | used while loading            |
|    8 | sector 5   | used while loading            |
|    9 | sector 6   | used while loading            |
|    a | sector 7   | used while loading            |
|    b | sector 8   | used while loading            |
|    c | sector 9   | used while loading            |
|    d | NMI/loader | used while loading            |
|    e | loader     | used while loading            |
|    f | loader     | used while loading            |

The only permanently reserved region is page 2.

Nothing reserves any specific regions of page 1, which is intended to
be used as the 6502 stack, in the usual 6502 stack fashion.

Anything "used while loading" is only used while loading. Once loading
is over, it can be discarded. Current plan is for each load to re-copy
anything required, on the basis that the time spent copying (~768
bytes, so maybe figure ~10,000 cycles?) will be dwarfed by any time
spent accessing the disk.

Regarding having all of page 2 reserved:

- IRQ1V is at $0204, and unavoidable, so at least this part of page 2
  will have to be reserved
- the OS memory clear flags are at $0258, and it'd be nice to be able
  to leave them set to $03, so that BREAK does something relatively
  clean even after all the OS workspace has been overwritten
- the BRK handler goes round the ROMs before doing a =JMP (BRKV)= -
  reserving all of page 2 might mean that it'd be possible to make BRK
  still work in some fashion by clearing out the ROMs table. This'd be
  nice for development, since BRK is often the end result of any
  wayward code execution

And it's not like there are any super compelling display addresses
lower than $300. A start address of $300 gives a useful number of rows
with some common strides:

| Stride | # Rows |
|--------+--------|
|    256 |    125 |
|    320 |    100 |
|    512 |   62.5 |
|    640 |     50 |

The 62.5*512 case is annoying, but going 256 bytes lower would mean a
start address of $200, overlapping key parts of page 2.

And 101 rows of 320 would need a spicy start address of $01C0.

** Page 2 use and notes

| Start | What                  | Notes                                   |
|-------+-----------------------+-----------------------------------------|
| $200  | Entry point           |                                         |
| $202  | BRKV                  | would be nice if this did something     |
| $204  | IRQ1V                 | IRQ handler preamble does =JMP ($0204)= |
| $206  | Entry point           |                                         |
| $208  | Entry point           |                                         |
| $20A  | Entry point           |                                         |
| $20c  | ???                   |                                         |
| $258  | OS memory clear flags | Best to keep this set to $03            |
| $259  | ???                   |                                         |

Keeping the OS memory clear flags set to 3 means there'll be a memory
clear on BREAK, and the OS won't get confused by whatever junk has
been written into its workspace. Makes things a bit tidier.

The entry points are designed to be called with =JSR=, rather than
being vectors. Only 2 bytes needed in each case, since 65c02 =BRA= can
be used.

(Or maybe some other arrangement would be better? To be continued.)

** =BRK= support

The original plan/hope was that BRK could be somehow made to work for
debugging purposes. There's a loop in the MOS that goes through the
ROMs and tries to call their service entry points, but what if the ROM
table were zeroed out? Maybe it could be made to work! It'd find no
valid ROMs and skip them all.

Sadly the standard BRK handling always calls ROM 15, and ROM 15
handles the BRK service call, and does a bunch of stuff to close the
*MOVE handles. Which is just going to make an unholy mess.

Safest to just do nothing, and you'll have to deal with any surprise
BRKs in an emulator.

* old initial transition stuff

#+begin_src 64tass
                  .section initial_transition_zp
  initial_transition_next_addr: .fill 2
  initial_transition_addr: .fill 2
                  .endsection
#+end_src

#+begin_src 64tass
  init_initial_transition: .block
                  stz initial_transition_next_addr+0
                  lda #$30
                  sta initial_transition_next_addr+1
                  rts                
                  .endblock

  update_initial_transition: .block
                  bit transition_current_state
                  bmi update_done ; taken if transition complete
                  
                  ; page in shadow RAM
                  lda #acccon.x
                  tsb acccon

                  lda initial_transition_next_addr+0
                  sta initial_transition_addr+0
                  lda initial_transition_next_addr+1
                  sta initial_transition_addr+1

                  ldx #80
                  ldy #0
  fill_row_loop:
                  lda #%00111111
                  sta (initial_transition_addr),y

                  clc
                  tya
                  adc #8
                  tay
                  bcc +
                  inc initial_transition_addr+1
  +
                  dex
                  bne fill_row_loop

                  inc initial_transition_next_addr+0
                  lda initial_transition_next_addr+0
                  and #7
                  bne +

                  clc
                  lda initial_transition_next_addr+0
                  adc #<632
                  sta initial_transition_next_addr+0
                  lda initial_transition_next_addr+1
                  adc #>632
                  sta initial_transition_next_addr+1
                  bpl +

                  sta transition_current_state ; set bit 7

  +
  update_done:
                  rts
                  

  ;                 ldx #0
  ;                 clc
  ; fill_row_loop:
  ;                 lda #%00111111
  ; store_byte0: sta $3000+0*128,x
  ; store_byte1: sta $3000+1*128,x
  ; store_byte2: sta $3000+2*128,x
  ; store_byte3: sta $3000+3*128,x
  ; store_byte4: sta $3000+4*128,x
  ;                 txa
  ;                 adc #8
  ;                 tax
  ;                 bpl fill_row_loop

  ;                 ldx #store_byte0-store_byte0
  ;                 jsr update_addr
  ;                 ldx #store_byte1-store_byte0
  ;                 jsr update_addr
  ;                 ldx #store_byte2-store_byte0
  ;                 jsr update_addr
  ;                 ldx #store_byte3-store_byte0
  ;                 jsr update_addr
  ;                 ldx #store_byte4-store_byte0
  ;                 jsr update_addr
  ; update_done:
  ;                 rts

  ; update_addr:
  ;                 inc store_byte0+1,x
  ;                 lda store_byte0+1,x
  ;                 and #7
  ;                 bne update_addr_done
  ;                 clc
  ;                 lda store_byte0+1,x
  ;                 adc #<(640-8)
  ;                 sta store_byte0+1,x
  ;                 lda store_byte0+2,x
  ;                 adc #>(640-8)
  ;                 sta store_byte0+2,x
  ;                 bpl update_addr_done

  ;                 ; if any of the addresses go over $8000, the
  ;                 ; transition is over.
  ;                 lda #$80
  ;                 sta initial_transition_state
                  
  ; update_done:
  ;                 rts
                  
                  .endblock
#+end_src


* palette

| Dec |  Bin | Hex | 1 bpp | 2 bpp | 4 bpp |
|-----+------+-----+-------+-------+-------|
|   0 | 0000 |   0 |     0 |     0 |     0 |
|   1 | 0001 |   1 |     0 |     0 |     1 |
|   2 | 0010 |   2 |     0 |     1 |     2 |
|   3 | 0011 |   3 |     0 |     1 |     3 |
|   4 | 0100 |   4 |     0 |     0 |     4 |
|   5 | 0101 |   5 |     0 |     0 |     5 |
|   6 | 0110 |   6 |     0 |     1 |     6 |
|   7 | 0111 |   7 |     0 |     1 |     7 |
|   8 | 1000 |   8 |     7 |     2 |     8 |
|   9 | 1001 |   9 |     7 |     2 |     9 |
|  10 | 1010 |   a |     7 |     3 |     a |
|  11 | 1011 |   b |     7 |     3 |     b |
|  12 | 1100 |   c |     7 |     2 |     c |
|  13 | 1101 |   d |     7 |     2 |     d |
|  14 | 1110 |   e |     7 |     3 |     e |
|  15 | 1111 |   f |     7 |     3 |     f |

* 64tass test

#+begin_example
-Wall --case-sensitive  --m65c02 --verbose-list --line-numbers --nostart -L "D:\tom\github\fdload_dfs/build/framework_bank.loader.lst" -o "D:\tom\github\fdload_dfs/build/framework_bank.loader.dat" "D:\tom\github\fdload_dfs\src\common\framework_bank.loader.s65" --labels-root=framework_bank_exports "--labels=D:\tom\github\fdload_dfs/build/framework_bank.loader.exports.asm" "--dump-labels" "--labels=D:\tom\github\fdload_dfs/build/framework_bank.loader.all.sym"
#+end_example

#+begin_example
-Wall --case-sensitive  --m65c02 --verbose-list --line-numbers --nostart -L "D:\tom\github\fdload_dfs/build/64tass_symbol_types.lst" -o "D:\tom\github\fdload_dfs/build/64tass_symbol_types.dat" "D:\tom\github\fdload_dfs\tests\64tass_dump_symbols\64tass_symbol_types.s65" "--dump-labels" "--labels=D:\tom\github\fdload_dfs/build/64tass_symbol_types.sym"
#+end_example

#+begin_example
--m65xx -Wall -Wno-implied-reg -Wno-portable -C --line-numbers --long-branch -L "D:\tom\github\fdload_dfs\build\beeblink.lst" -o "D:\tom\github\fdload_dfs\build\beeblink.rom" "D:\tom\github\beeblink\beeb\beeblink.s65" -Dlink_tube_serial=true --debug-labels "--labels=D:\tom\github\fdload_dfs\build\beeblink.sym" -DVERSION=\"test\" -DCOMMIT=\"N/A\" -DBUILD_INFO=\"N/A\"
#+end_example


--debug-labels

* eof
