                .include '../shared_constants.asm'
                .include '../../dependencies/beeb/include/beeb.s65'

*=0
screen_index: .fill 1

screens=[screen0,screen1,screen2,screen3,screen4]
                
*=$8000

                ldx #15
-
                lda mode_1_palette,x
                sta video_ula_palette
                dex
                bpl -

                .if MODE==1
                lda #$d8        ; mode 1
                .elif MODE==5
                lda #$c4        ; mode 5
                .else
                .error 
                .endif
                sta video_ula_control

                lda #8
                sta $fe00
                stz $fe01

                ; display shadow, page in main
                lda #acccon.d
                sta acccon

                ; stz acccon

loop:
                ldx screen_index
                lda screen_lsbs,x
                sta framework_decomp_src+0
                lda screen_msbs,x
                sta framework_decomp_src+1

                stz framework_decomp_dest+0
                lda #$30
                sta framework_decomp_dest+1

                jsr framework_decomp_data

                lda acccon
                eor #acccon.d|acccon.x
                sta acccon

                lda screen_index
                inc a
                cmp #len(screens)
                bcc +
                lda #0
+
                sta screen_index

                jmp loop
                
mode_1_palette:
                .for i=0,i<16,i+=1
                .block
logical=i
physical:=0
                .if (i&8)!=0
physical|=2
                .endif
                .if (i&2)!=0
physical|=1
                .endif
                .byte logical<<4|physical^7
                .endblock
                .endfor

screen_lsbs: .byte <screens
screen_msbs: .byte >screens

screen_path: .sfunction _index,format("../../build/screens1.screen%d.mode%d.dat.zx02",_index,MODE)
                
screen0: .binary screen_path(0)
screen1: .binary screen_path(1)
screen2: .binary screen_path(2)
screen3: .binary screen_path(3)
screen4: .binary screen_path(4)
                .cerror *>$c000
                