                .include '../shared_constants.asm'
                .include '../../dependencies/beeb/include/beeb.s65'
                .include '../b2_constants.asm'
                .include '../shared_64tass.s65'

*=0
screen_index: .fill 1
transition_done: .fill 1

screens=[screen0,screen1,screen2,screen3,screen4]
                
*=$8000
                ; TODO - some better mechanism than this, surely
                .if MODE==1
                .enable_symbol_group symbol_group_screens1_mode1
                .elsif MODE==5
                .enable_symbol_group symbol_group_screens1_mode5
                .else
                .error
                .endif
                
                ; page in whichever RAM isn't displayed
                lda acccon
                lsr a          ; C=1 if displaying shadow; C=0 if main
                lda #acccon.y|acccon.x ; assume displayng main
                bcc +                  ; taken if indeed displaying main
                eor #acccon.d|acccon.x
+
                sta acccon

                ; stz acccon

loop:
                ldx screen_index
                lda screen_lsbs,x
                sta framework_decomp_src+0
                lda screen_msbs,x
                sta framework_decomp_src+1

                stz framework_decomp_dest+0
                lda #$30
                sta framework_decomp_dest+1

                jsr framework_decomp_data

                bit transition_done
                bmi next_screen ; taken if transition complete

transition_finished_loop:
                lda transition_current_state
                cmp #$80        ; screen full of black?
                bne transition_finished_loop

                jsr framework_stop_transition

                .if MODE==1
                lda #$d8        ; mode 1
                .elif MODE==5
                lda #$c4        ; mode 5
                .else
                .error 
                .endif
                sta video_ula_control

                ldx #15
-
                lda mode_1_palette,x
                sta video_ula_palette
                dex
                bpl -

                lda #$80
                sta transition_done

next_screen:
                lda acccon
                eor #acccon.d|acccon.x
                sta acccon

                inc screen_index
                lda screen_index
                cmp #len(screens)
                bcc loop

                rts
                
mode_1_palette:
                .for i=0,i<16,i+=1
                .block
logical=i
physical:=0
                .if (i&8)!=0
physical|=2
                .endif
                .if (i&2)!=0
physical|=1
                .endif
                .byte logical<<4|physical^7
                .endblock
                .endfor

screen_lsbs: .byte <screens
screen_msbs: .byte >screens

screen_path: .sfunction _index,format("../../build/screens1.screen%d.mode%d.dat.zx02",_index,MODE)
                
screen0: .binary screen_path(0)
screen1: .binary screen_path(1)
screen2: .binary screen_path(2)
screen3: .binary screen_path(3)
screen4: .binary screen_path(4)
                .cerror *>$c000
                