                .include '../../dependencies/beeb/include/beeb.s65'
                .include '../shared_constants.asm'
                .include 'dfs.s65'
                .include 'zx02_decomp.s65'
                .include 'fdload.s65'
                .include '../b2_constants.asm'
                .include '../shared_64tass.s65'

;-------------------------------------------------------------------------

*=$e0
                .dsection zx02_workspace_zp
                .dsection fdload_workspace_zp

; don't overlap with $f4.
                .cerror *>$f4,format("$%02x",*)
*=$f5
                .dsection dfs_workspace_zp

                ; don't overlap with $fc.
                .cerror *>$fc

                ; fd - todo
                ; fe - todo
                ; ff - vsync counter

;-------------------------------------------------------------------------

*=framework_bank_loader_code_begin
                .dsection framework_bank_code
                .dsection dfs_code
main_ram_stuff_unrelocated_begin:
                .logical $d00-(fdload_ram_code-main_ram_stuff_relocated_begin)
main_ram_stuff_relocated_begin:
                .cerror *<loader_main_ram_code_begin
                .dsection loader_code_main
                .dsection zx02_code
                .dsection zx02_workspace_main
                .dsection dfs_workspace_main
fdload_ram_code:
                .dsection fdload_code
                .dsection dfs_code_main
                .dsection loader_workspace_main
                .cerror *>=loader_main_ram_code_end
                .endlogical
main_ram_stuff_unrelocated_end:
                .cerror *>framework_bank_loader_code_end,format('*=$%04x',*)

;-------------------------------------------------------------------------

; these symbols are exposed to BeebAsm code as well. It'd be nice to
; have them exported with framework_bank_exports, then included in
; shared_constants.asm, but BeebAsm's include directive and 64tass's
; include directive aren't syntactically compatible. So there's an
; explicit constant in shared_constants.asm and a .cerror here to make
; sure they don't get out of line.

                .cerror ZX0_src!=framework_decomp_src
                .cerror ZX0_dst!=framework_decomp_dest
                
;-------------------------------------------------------------------------

; these symbols are exported for use by the BeebAsm part of the ROM
; code.
                
framework_bank_exports: .block
; The rom_ symbols are accessible only when the ROM is paged in.
framework_rom_copy_in=copy_in
framework_rom_set_default_irq_handler=set_default_irq_handler
framework_rom_page02_unrelocated=page02_unrelocated

; The ram_ symbols are accessible after rom_copy_in has been called.
framework_ram_loader_load_file=loader_load_file_3 ; can we get a better name here please.
framework_ram_decomp=decomp
framework_ram_prepare_decomp_single_part=prepare_decomp_single_part
framework_ram_fdload_init=fdload_init
framework_ram_fdload_read1=fdload_read1
framework_ram_fdload_wait_not_busy=fdload_wait_not_busy
                
; The zp_ symbols are zero page.
framework_zp_fdload_track=fdload_track
framework_zp_fdload_addr_msb=fdload_addr_msb
framework_zp_fdload_side=fdload_side
framework_zp_fdload_sector=fdload_sector

; The page02_ symbols are in page $02.
framework_page02_transition_t2_routine_addr=page02_standard_irq_handler.transition_t2_routine_addr
framework_page02_transition_t2_acccon_value=page02_standard_irq_handler.transition_t2_acccon_value
framework_page02_start_next_part=page02_start_next_part
framework_page02_transition_vsync_routine_addr=page02_standard_irq_handler.transition_vsync_routine_addr
framework_page02_bra_skip_vsync=page02_standard_irq_handler.bra_skip_vsync
framework_page02_transition_t2_lda_acccon=page02_standard_irq_handler.transition_t2_lda_acccon
framework_page02_transition_t2_done=page02_standard_irq_handler.transition_t2_done
                .endblock

;-------------------------------------------------------------------------

                .section loader_workspace_main
loader_arguments: .block

; if the address MSB is 0, load to the file's load address. (Loading
; into zero page is not supported. Sorry!)
load_addr: .fill 2

; if the address MSB is 0, no execution takes place.
exec_addr: .fill 2

; romsel value for use during the load, or $ff to use current.
bank: .fill 1

; drive to load from: 0 or 2.
drive: .fill 1
                .endblock

loader_decomp: .fill 1
                .endsection loader_workspace_main

;-------------------------------------------------------------------------

                .section loader_code_main

loader_load_file_3: .block
                stx dfs_name+0
                sty dfs_name+1

                ; save load address and drive number
                ldy #0
copy_loader_arguments_loop:
                lda (dfs_name),y
                sta loader_arguments,y

                iny
                cpy #size(loader_arguments)
                bne copy_loader_arguments_loop

                ; save name
                jsr dfs_copy_name

                jsr page02_select_bank
                phy             ; save old ROM bank

                jsr prepare_load

                pla             ; A=old ROM bank
                pha             ; store old ROM bank

                ; handle the 0 byte case.
                lda dfs_length+0
                ora dfs_length+1
                beq done

                ; use a different bank for the load?
                ldx loader_arguments.bank
                cpx #$ff        ; X=$ff means use current bank
                beq +           ; taken if using current bank
                txa             ; use loader arguments bank
+
                sta romsel      ; select appropriate ROM bank for load

                ; Buffer 0 is the write buffer to start with.
                lda #>loader_main_ram_sector_buffer_0
                sta fdload_addr_msb

                ; Nothing in the read buffer initially.
                ;
                ; The ZX0_src pointer is used for both cases. Save a
                ; couple of bytes.
                stz ZX0_src+0
                stz ZX0_src+1
                
loop:
                ; Initiate load into write buffer (if any) and advance
                ; to next location.
                lda fdload_addr_msb
                beq check_read_buffer
                
                jsr fdload_read1
                jsr fdload_next_location

check_read_buffer:
                ; Got any data in the read buffer?
                lda ZX0_src+1
                beq next        ; taken if no data to unpack

                ; Is the data compressed?
                bit loader_decomp
                bpl uncompressed ; taken if uncompressed

                ; Unpack the data.
                jsr decomp

                ; Bail out if data exhausted.
                lda ZX0_saved_state_size
                beq done

                ; Continue.
                bra next

uncompressed:
                ; X=number of bytes to copy (or 0 to copy 256)
                ldx #0
                lda dfs_length+1
                bne +
                ldx dfs_length+0
+
                ldy #0
copy_uncompressed_loop:
                lda (ZX0_src),y
                sta (ZX0_dst),y
                iny
                dex
                bne copy_uncompressed_loop

                ; dest+=256
                inc ZX0_dst+1

                ; Any more?
                lda dfs_length+1
                beq done        ; taken if that was the last page
                dec dfs_length+1
                bne next ; taken if that was definitely not the last page
                lda dfs_length+0
                beq done        ; taken if that was the last page

next:
                ; Most recent write address is where to read from next.
                lda fdload_addr_msb
                sta ZX0_src+1

                ; Write to the other buffer next time.
                eor #>(loader_main_ram_sector_buffer_0^loader_main_ram_sector_buffer_1)
                sta fdload_addr_msb
                
                bra loop
                
done:
                ; ...
                jsr fdload_wait_not_busy

                ; call exec routine
                jsr call_exec_address

                ; restore original ROM bank
                pla
                sta romsel
                
                ; 
                rts

call_exec_address:
                jmp (dfs_exec)
                
                .endblock

                .endsection
                
;-------------------------------------------------------------------------

                .section framework_bank_code

; set_mode_2: .block
;                 ; N.B., this doesn't set the scroll wraparound size
;                 ldx #13
; init_crtc_loop:
;                 stx $fe00
;                 lda crtc_2MHz,x
;                 sta $fe01
;                 dex
;                 bpl init_crtc_loop

;                 lda #$f4
;                 sta video_ula_control

;                 lda #0
; init_palette_loop:
;                 eor #7          ; ULA colours are inverted
;                 sta video_ula_palette
;                 eor #7          ; undo the above
;                 clc
;                 adc #$11
;                 bcc init_palette_loop

;                 lda #$06
;                 sta video_ula_palette

;                 rts
; crtc_2MHz:
;                 .byte $7F            ; R0 - Horizontal Total
;                 .byte 80             ; R1 - Horizontal Displayed
;                 .byte $62            ; R2 - Horizontal Sync
;                 .byte $28            ; R3 - Sync Width (%vvvvhhhh)
;                 .byte $26            ; R4 - Vertical Total
;                 .byte $00            ; R5 - Vertical Total Adjust
;                 .byte $20            ; R6 - Vertical Displayed
;                 .byte $22            ; R7 - Vertical Sync Position
;                 .byte $01            ; R8 - Interlace/Delay
;                 .byte $07            ; R9 - Scan lines per character
;                 .byte $20            ; R10 - Cursor blink/start
;                 .byte 8              ; R11 - Cursor End
;                 .byte $06            ; R12 - screen start MSB
;                 .byte $00            ; R13 - screen start LSB
;                 .endblock

;-------------------------------------------------------------------------
;
; error thing
;
error: .block
                ; should really print these values somewhere...
                sei
                pha             ; save error code

                lda #$40
                sta $0d00

                lda #$d0
                sta fdc.command

                ldx #13
init_crtc_loop:
                stx $fe00
                lda crtc_mode7,x
                sta $fe01
                dex
                bpl init_crtc_loop

                lda #$4B
                sta video_ula_control

                ; display main RAM, page in main RAM
                lda #acccon.d|acccon.x
                trb acccon

                ldx #0
                lda #255
cls_loop:
                sta $7c00,x
                sta $7d00,x
                sta $7e00,x
                sta $7f00,x
                inx
                bne cls_loop

                pla
                sta $7c00+0*40  ; error code

                lda fdload_side
                clc
                adc #'0'
                sta $7c00+1*40+0

                ldx #size(dfs_name_buffer)-1
copy_dfs_name_loop:
                lda dfs_name_buffer,x
                sta $7c00+2*40,x

                txa
                clc
                adc #'0'
                sta $7c00+3*40,x
                
                dex
                bpl copy_dfs_name_loop

halt:
                bra halt

crtc_mode7:
                .byte $3f       ; R0 - Horizontal Total
                .byte $28       ; R1 - Horizontal Displayed
                .byte $33       ; R2 - Horizontal Sync
                .byte $24       ; R3 - Sync Width (%vvvvhhhh)
                .byte $1e       ; R4 - Vertical Total
                .byte $02       ; R5 - Vertical Total Adjust
                .byte $19       ; R6 - Vertical Displayed
                .byte $1b       ; R7 - Vertical Sync Position
                .byte $93       ; R8 - Interlace/Delay
                .byte $12       ; R9 - Scan lines per character
                .byte $20       ; R10 - Cursor blink/start
                .byte 19        ; R11 - Cursor End
                .byte $28       ; R12 - start MSB
                .byte $00       ; R13 - start LSB
                .endblock 
                
;-------------------------------------------------------------------------
;
; Prepare for a DFS file load.
;
; Entry: dfs file name set up
;        loader_arguments set up
;
; Exit: C=0 if file not found
;       else:
;       ?fdload_track = start track for read
;       ?fdload_sector = start sector for read
;       ?fdload_side = disk side for road
;       (ZX0_dst) = address to load to
;       ...plus all the other dfs metadata
;       bit 7 of ?loader_decomp is set if file looks compressed
;       if file looks compressed, ZX02 is prepared for a multi-part decomp
prepare_load: .block
                ; form address of appropriate cat buffer. Each one is
                ; 2 sectors; the drive number can act as the offset.
                lda loader_arguments.drive
                and #2          ; drive 0/drive 2
                clc
                adc #>framework_bank_cat_buffers
                sta dfs_cat+1
                stz dfs_cat+0
                jsr dfs_find_entry
                bcs found

                lda #'f'
                jmp error

found:
                ; Sort out load address
                lda loader_arguments.load_addr+1
                beq got_load_address ; taken if file's load address should be used
                sta dfs_load+1
                lda loader_arguments.load_addr+0
                sta dfs_load+0
got_load_address:
                lda dfs_load+0
                sta ZX0_dst+0
                lda dfs_load+1
                sta ZX0_dst+1

                ; Sort out exec address
                lda loader_arguments.exec_addr+1
                beq got_exec_address ; taken if file's exec address is good
                cmp #$ff
                bne use_loader_exec_address

                ; use null exec address
                lda #<page02_rts
                sta loader_arguments.exec_addr+0
                lda #>page02_rts
use_loader_exec_address:
                sta dfs_exec+1
                lda loader_arguments.exec_addr+0
                sta dfs_exec+0
got_exec_address:

                ; Copy DFS location.
                lda dfs_track
                sta fdload_track
                lda dfs_sector
                sta fdload_sector
                lda loader_arguments.drive
                and #2
                sta fdload_side

                ; Assume file not compressed.
                stz loader_decomp

                ; Is it a compressed file? Prepare ZX02 if so.
                lda dfs_dir
                jsr dfs_find_entry.toupper ; ugh
                cmp #'Z'
                bne zx02_prepared
                
                ; Set loader_decomp bit 7. C=1 due to the cmp.
                ror loader_decomp

                ; Prepare ZX02.
                jsr prepare_decomp_multi_part

zx02_prepared:

                sec
done:
                rts
                .endblock
                
;-------------------------------------------------------------------------
;
; Copy loader code into main RAM.
;
; Preserves: Y
copy_in: .block
                ldx #0
loop:
main_ram_stuff_size=main_ram_stuff_unrelocated_end-main_ram_stuff_unrelocated_begin
num_pages=>(main_ram_stuff_size+255)
                .cerror num_pages<2 ; need a rethink if this hits...
                .for page=0,page<num_pages,page+=1
                .block
                .if page<num_pages-1
_offset=page*256
                .else
_offset=main_ram_stuff_size-256
                .endif
                lda main_ram_stuff_unrelocated_begin+_offset,x
                sta main_ram_stuff_relocated_begin+_offset,x
                .endblock
                .endfor
                inx
                bne loop

                .enable_symbol_group symbol_group_main_ram_loader
                
                rts
                .endblock

;-------------------------------------------------------------------------

set_default_irq_handler:
                php
                sei
                lda #<page02_standard_irq_handler ; TODO: fix naming
                sta irq1v+0
                lda #>page02_standard_irq_handler
                sta irq1v+1

                ; disable all IRQs on both VIAs
                lda #$7f
                sta system_via.ier
                sta user_via.ier

                ; put T2 in timed interrupt mode
                lda #$20        ; T2 flag
                trb system_via.pcr ; 0=timed interrupt

                ; enable system VIA CA1 (vsync)+T2
                lda #$80|VIAIRQ.ca1|VIAIRQ.t2
                sta system_via.ier

                plp
                rts

;-------------------------------------------------------------------------

page02_unrelocated:
                .logical $200
                
                .cerror *!=framework_load_file
                bra page02_load_file

                .cerror *!=framework_stop_transition
                bra stop_transition

                .cerror *!=irq1v
                .word page02_standard_irq_handler

                .cerror *!=framework_decomp_data
                bra page02_decomp_data

                .cerror *!=framework_decomp_data_2
                bra page02_decomp_data_2

                .cerror *!=framework_update_music
                bra page02_update_music

                .cerror *!=framework_set_default_irq_handler
                bra page02_set_default_irq_handler

;-------------------------------------------------------------------------

page02_load_file:
                jsr page02_copy_in
                jmp loader_load_file_3

;-------------------------------------------------------------------------

page02_decomp_data:
                jsr page02_copy_in
page02_decomp_data_2:
                jsr prepare_decomp_single_part
                jmp decomp

;-------------------------------------------------------------------------

page02_select_bank:
                ldy romsel
                lda #framework_bank
                sta romsel
page02_rts:
                rts

;-------------------------------------------------------------------------

page02_update_music: .block
                lda romsel
                sta relda+1
                lda #music_bank
                sta romsel
                jsr music_bank_update
relda: lda #$ff
                sta romsel
                rts
                .endblock

;-------------------------------------------------------------------------

page02_set_default_irq_handler:
                jsr page02_select_bank
                jmp set_default_irq_handler

;-------------------------------------------------------------------------

stop_transition:
                jsr page02_select_bank
                phy
                ldx #0          ; null transition
                jsr framework_bank_init_transition
                ply
                sty romsel
                rts

;-------------------------------------------------------------------------

                ; Ensure $0258 is $03 - meaning a memory clear on the
                ; next break.
                ;
                ; $03 is a 1-cycle 65c02 NOP, so just fill the whole
                ; region. Too much code inserted before, and there'll
                ; be an error - but with a bit of shuffling, it can
                ; just fall through this region and carry on.
                .fill $259-*,3
                
;-------------------------------------------------------------------------

page02_copy_in:
                phx
                phy
                jsr page02_select_bank
                jsr copy_in
                sty romsel
                ply
                plx
                rts

;-------------------------------------------------------------------------

page02_start_next_part:
                lda #part_main_bank
                sta romsel
                lda #>(page02_select_bank-1)
                pha
                lda #<(page02_select_bank-1)
                pha
                jmp $8000

;-------------------------------------------------------------------------

page02_standard_irq_handler: .block
                lda system_via.ifr
                bpl page02_null_irq_handler

test_ca1:
                bit #VIAIRQ.ca1
                beq test_t2
                
                lda #VIAIRQ.ca1
                sta system_via.ifr
                ; TODO this probably wants to be configurable
;t2_val=(256+(312-272))*64
t2_val=260*64
                lda #<t2_val
                sta system_via.t2c_l
                lda #>t2_val
                sta system_via.t2c_h

                inc framework_vsync_counter

bra_skip_vsync:
                ; can be replaced with $02 (NOP #xx) to have the next
                ; bit of code executed. Reinstate $80 (BRA rel) to
                ; have it skip the vsync bit.
                bra vsync_done

                cld
                phx
                phy
                lda romsel
                pha

                lda #framework_bank
                sta romsel

transition_vsync_routine_addr=*+1
                jsr $0000       ; no useful address needed

                pla
                sta romsel
                ply
                plx

vsync_done:
page02_null_irq_handler:
                lda $fc
                rti

test_t2:
                bit #VIAIRQ.t2
                beq page02_null_irq_handler

                lda #VIAIRQ.t2
                sta system_via.ifr

                ; the vsync IRQ is coming up, and it mustn't be
                ; missed! Get things ready so that IRQs can be enabled
                ; again so that it can be handled.
                ; 
                ; The interrupt routine is re-entrant enough, but a
                ; bit of care has to be taken over the A value saved
                ; in $FC.
                
                cld
                lda $fc
                pha
                phx
                phy
                lda romsel
                pha
                lda acccon
                pha

                cli

                .if b2_debug!=0
                lda #2          ; green=music
                sta $fc5d
                .endif

                lda #music_bank
                sta romsel
                jsr music_bank_update

                .if b2_debug!=0
                lda #1          ; red=transition
                sta $fc5d
                .endif

                ; this lda # is replaced with `bra transition_t2_done'
                ; if the update routine is null.
transition_t2_lda_acccon:
                lda #acccon.y
                sta acccon

                lda #framework_bank
                sta romsel
transition_t2_routine_addr=*+1
                jsr page02_rts

transition_t2_done:
                inc framework_t2_counter
                
                .if b2_debug!=0
                stz $fc5d       ; reset border colour
                .endif


                pla
                sta acccon
                pla
                sta romsel
                ply
                plx
                pla
                rti
                .endblock

;-------------------------------------------------------------------------

                .fill $300-*,0
                .endlogical
                .cerror *-page02_unrelocated!=256

                .endsection framework_bank_code

;-------------------------------------------------------------------------
 