                .include '../../dependencies/beeb/include/beeb.s65'
                .include '../shared_constants.asm'
                .include '../../build/framework_bank.loader.exports.asm'

;-------------------------------------------------------------------------

check_addr: .macro name,wanted,got
                .cerror (\got)!=(\wanted),format("%s mismatch: got $%04x, wanted $%04x",(\name),(\got),(\wanted))
                .endmacro
                
;-------------------------------------------------------------------------

*=$200

                .cerror *!=loader_load_file
                bra loader_load_file_impl

                .cerror *!=framework_select_bank
                bra framework_select_bank_impl

                .cerror *!=irq1v
                .word default_irq_handler

                .cerror *!=loader_decomp_data
                bra loader_decomp_data_impl

                .cerror *!=loader_decomp_data_2
                bra loader_decomp_data_2_impl

framework_select_bank_impl:
                ldy romsel
                lda #framework_bank
                sta romsel
                rts

loader_load_file_impl:
                jsr copy_in
                jmp framework_ram_loader_load_file

loader_decomp_data_impl:
                jsr copy_in
loader_decomp_data_2_impl:
                jsr framework_ram_prepare_decomp_single_part
                jmp framework_ram_decomp

copy_in:
                phx
                phy
                jsr framework_select_bank
                jsr framework_rom_copy_in
                sty romsel
                ply
                plx
                rts
                
                .fill $258-*,0
                .byte 3         ; *FX200,3

                .check_addr "framework_transition_irq_handler",framework_transition_irq_handler,*
transition_irq_handler:
                lda system_via.ifr
                bpl default_irq_handler

                and #VIAIRQ.ca1 ; vsync
                beq default_irq_handler

                sta system_via.ifr ; clear interrupt flag
                
                cld
                lda romsel
                pha
                lda acccon
                pha
                lda #framework_bank
                sta romsel
                phx
                phy
                
                .check_addr "framework_transition_routine_addr",framework_transition_routine_addr,*+1
                jsr $ffff
                
                ply
                plx
                pla
                sta acccon
                pla
                sta romsel
default_irq_handler:
                lda $fc
                rti

                .fill $300-*,0
                
                .cerror *>$300

;-------------------------------------------------------------------------
