                .include '../../dependencies/beeb/include/beeb.s65'
                .include '../shared_constants.asm'
                .include '../../build/framework_bank.loader.exports.asm'
                .include 'constants.asm'

;-------------------------------------------------------------------------

; constants.asm is not authoritative, so there's a helpful message if
; the addresses change.
check_addr: .macro name,wanted,got
                .cerror (\got)!=(\wanted),format("%s mismatch: got $%04x, wanted $%04x (constants.asm might need fixing up)",(\name),(\got),(\wanted))
                .endmacro
                
;-------------------------------------------------------------------------

*=$200
                .cerror *!=loader_load_file
                bra loader_load_file_impl

                .cerror *!=framework_next_part
                bra framework_next_part_impl

                .cerror *!=irq1v
                .word default_irq_handler

                .cerror *!=loader_decomp_data
                bra loader_decomp_data_impl

                .cerror *!=loader_decomp_data_2
                bra loader_decomp_data_2_impl

                .check_addr "framework_select_bank",framework_select_bank,*
                ldy romsel
                lda #framework_bank
                sta romsel
                rts

loader_load_file_impl:
                jsr copy_in
                jmp framework_ram_loader_load_file

loader_decomp_data_impl:
                jsr copy_in
loader_decomp_data_2_impl:
                jsr framework_ram_prepare_decomp_single_part
                jmp framework_ram_decomp

framework_next_part_impl:
                jsr framework_select_bank
                lda framework_next_part_rts_addr+1
                pha
                lda framework_next_part_rts_addr+0
                pha
                rts

                .fill $258-*,0
                .byte 3         ; *FX200,3

copy_in:
                phx
                phy
                jsr framework_select_bank
                jsr framework_rom_copy_in
                sty romsel
                ply
                plx
                rts

                .check_addr "framework_start_next_part",framework_start_next_part,*
                pla
                sta framework_next_part_rts_addr+0
                pla
                sta framework_next_part_rts_addr+1
                lda #part_main_bank
                sta romsel
                jmp $8000
                

                .check_addr "framework_transition_irq_handler",framework_transition_irq_handler,*
                lda system_via.ifr
                bpl default_irq_handler

                cld
                phx
                phy
                ldx romsel
                phx
                ldx acccon
                phx

                bit #VIAIRQ.ca1
                bne handle_ca1

                bit #VIAIRQ.t2
                bne handle_t2

                ; if neither case is true: what a waste of time. But
                ; that isn't suppose to happen!

finish_irq:
                pla
                sta acccon
                pla
                sta romsel
                ply
                plx
default_irq_handler:
                lda $fc
                rti

handle_ca1:
                lda #VIAIRQ.ca1
                sta system_via.ifr

t2_val=(256+(312-272))*64
                
                lda #<t2_val
                sta system_via.t2c_l
                lda #>t2_val
                sta system_via.t2c_h

                ; TODO: music...

                bra finish_irq

handle_t2:
                lda #VIAIRQ.t2
                sta system_via.ifr

                lda #framework_bank
                sta romsel

                ; the vsync IRQ is coming up, and it mustn't be
                ; missed! Enable IRQs so that it can be handled. The
                ; interrupt routine is re-entrant, so nested
                ; invocations are no problem.
                cli
                
                .check_addr "framework_transition_routine_addr",framework_transition_routine_addr,*+1
                jsr $ffff
                bra finish_irq
                
framework_next_part_rts_addr: .word $8000-1

                .fill $300-*,0
                
                .cerror *>$300

;-------------------------------------------------------------------------
